### ISSUE TITLE
where can i see lecture i cant found on pluralsight 

### ISSUE THREAD

**Issue by teamsmiley** [KevinDockx/OpenIDConnectInDepth#3]
want to watch lecture but i cant find out this lecture.

can you give me link?

**Comment by pankajsri03** [comment]
I need thePluralsight course link for this repo @KevinDockx  . Can I get some help.
Does this repo has plularsight coure ?

**Comment by KevinDockx** [comment]
There's no course related to this code - the code in this repo is something I've used when speaking at a few conferences.
